### ISSUE TITLE
How does connect-the-dots work?

### ISSUE THREAD

**Issue by vonHabsi** [plexus/dotfiles#1]
How does connect-the-dots work?

**Comment by plexus** [comment]
why are you asking? and how did you come across this repo?

**Comment by vonHabsi** [comment]
You mentioned it in the Chemacs2 docs.

**Comment by plexus** [comment]
Right, it's a script that symlinks these dotfiles to your home directory, dealing with various edge cases like if the link already exists, if it points to a different file, if there's a regular file in the way, and so forth.

Have a look at the code, it should be fairly readable. It'll print out a status report for each link.
